### ISSUE TITLE
Flash of unstyled content

### ISSUE THREAD

**Issue by jpmckinney** [ClaudioMendoncaDesign/open-gazettes-interface#15]
On Firefox

**Comment by claudioccm** [comment]
I don't see this issue. Tried it here, but can't really see the flash. Usually these flashes are caused by loading order. I also checked that, and the styles are being loaded on the head, so there is no reason it should be flashing. 

I work with a former Mozilla frontend developer, once I can replicate the flash, I will ask for his help. :)

**Comment by jpmckinney** [comment]
Ah - it's only happening in development - maybe because my local server delivers assets slowly.
